# Generated by Django 6.0.3 on 2026-07-08 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchenbooking',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='kitchenbooking',
            name='student',
        ),
        migrations.DeleteModel(
            name='KitchenSlot',
        ),
        migrations.DeleteModel(
            name='KitchenBooking',
        ),
    ]
