# Generated by Django 6.0.7 on 2026-07-31 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.CharField(blank=True, choices=[('B40', 'B40'), ('M40', 'M40'), ('T20', 'T20'), ('OTHERS', 'Others')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
