# Generated by Django 6.0.7 on 2026-07-31 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_category_student_last_synced_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.CharField(blank=True, choices=[('B40', 'B40'), ('M40', 'M40'), ('OTHERS', 'Others')], max_length=10, null=True),
        ),
    ]
