# Generated by Django 6.0.4 on 2026-08-02 06:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetmaintenance',
            options={'ordering': ['-start_date']},
        ),
        migrations.RemoveField(
            model_name='assetmaintenance',
            name='maintenance_date',
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='end_date',
            field=models.DateField(blank=True, help_text='Tarikh aset dipulangkan selepas penyelenggaraan selesai. Kosongkan jika aset masih dalam penyelenggaraan.', null=True),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Tarikh aset dibawa keluar dari dapur untuk penyelenggaraan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('active', 'Aktif'), ('maintenance', 'Dalam Penyelenggaraan'), ('disposed', 'Dilupuskan')], default='active', max_length=20),
        ),
    ]
