# Generated by Django 6.0.4 on 2026-08-02 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_alter_assetmaintenance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Bilangan unit dilupuskan'),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Bilangan unit dihantar untuk penyelenggaraan'),
        ),
        migrations.AlterField(
            model_name='assetdisposal',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposal_records', to='asset.asset'),
        ),
    ]
