# Generated by Django 6.0.4 on 2026-08-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_asset_quantity_assetdisposal_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='image',
            field=models.ImageField(blank=True, help_text='Gambar rujukan aset ini', null=True, upload_to='assets/'),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='photo',
            field=models.ImageField(blank=True, help_text='Gambar bukti pelupusan', null=True, upload_to='asset_disposal/'),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='photo_after',
            field=models.ImageField(blank=True, help_text='Gambar bukti selepas aset dipulangkan / diselenggara', null=True, upload_to='asset_maintenance/after/'),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='photo_before',
            field=models.ImageField(blank=True, help_text='Gambar keadaan aset semasa dihantar untuk penyelenggaraan', null=True, upload_to='asset_maintenance/before/'),
        ),
    ]
