# Generated by Django 6.0.6 on 2026-07-15 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchens', '0002_kitchen_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchen',
            name='manager',
        ),
    ]
