# Generated by Django 6.0.6 on 2026-07-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchens', '0003_remove_kitchen_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('maintenance', 'Under Maintenance'), ('closed', 'Closed')], default='active', help_text='Operational state shown to students — separate from is_active, which controls whether the kitchen appears in the system at all.', max_length=20),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='status_note',
            field=models.CharField(blank=True, help_text="e.g. 'Closed for deep cleaning until Friday'", max_length=255),
        ),
    ]
