# Generated by Django 6.0.6 on 2026-07-26 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchens', '0005_volunteershift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteershift',
            name='kitchen',
        ),
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('faculty', models.CharField(blank=True, max_length=255)),
                ('kolej', models.CharField(blank=True, help_text='Residential college', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profiles', to='kitchens.kitchen')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='volunteershift',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='kitchens.volunteerprofile'),
        ),
    ]
