# Generated by Django 6.0.6 on 2026-07-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchens', '0006_remove_volunteershift_kitchen_volunteerprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='matrik_no',
            field=models.CharField(blank=True, help_text='Matriculation number', max_length=50),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
