# Generated by Django 6.0.4 on 2026-07-31 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchens', '0007_volunteerprofile_matrik_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. '7am-11am Penyediaan Makanan'", max_length=100)),
                ('slot_type', models.CharField(choices=[('food_prep', 'Penyediaan Makanan'), ('customer_service', 'Krew Khidmat Pelanggan')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveSmallIntegerField(default=2)),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_slots', to='kitchens.kitchen')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_shifts', to='kitchens.volunteerprofile')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_shifts', to='kitchens.shiftslot')),
            ],
            options={
                'ordering': ['date', 'slot__start_time'],
                'constraints': [models.UniqueConstraint(fields=('slot', 'volunteer', 'date'), name='unique_volunteer_slot_per_day')],
            },
        ),
    ]
