# Generated by Django 6.0.3 on 2026-07-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('management', 'Management'), ('volunteer', 'Volunteer'), ('student', 'Student')], max_length=20),
        ),
    ]
