# Generated by Django 6.0.6 on 2026-07-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory/')),
                ('stock_in', models.PositiveIntegerField(default=0)),
                ('stock_out', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('donation', 'Donation'), ('purchase', 'Purchase'), ('sponsor', 'Sponsor'), ('other', 'Other')], default='donation', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
