# Generated by Django 6.0.6 on 2026-07-05 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_inventoryitem_stock_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='source',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='image',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='reference_name',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(default='kg', max_length=50),
        ),
        migrations.CreateModel(
            name='SourceInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('donation', 'Donation'), ('purchase', 'Purchase'), ('sponsor', 'Sponsor'), ('supplier', 'Supplier'), ('other', 'Other')], max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_stocks', to='inventory.inventoryitem')),
            ],
            options={
                'unique_together': {('item', 'source')},
            },
        ),
    ]
