# Generated by Django 6.0.6 on 2026-07-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_inventoryitem_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='stock_proofs/'),
        ),
    ]
