# Generated by Django 6.0.6 on 2026-07-05 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventoryrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrequest',
            name='new_item_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventoryrequest',
            name='new_item_unit',
            field=models.CharField(default='kg', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryrequest',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem'),
        ),
    ]
