# Generated by Django 6.0.6 on 2026-07-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventoryrequest_new_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='purpose',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
