# Generated by Django 6.0.6 on 2026-07-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_stockmovement_location_stockmovement_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='context',
            field=models.CharField(choices=[('management', 'Management'), ('volunteer', 'Volunteer')], default='management', max_length=20),
        ),
    ]
