# Generated by Django 6.0.3 on 2026-07-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_stockmovement_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='context',
            field=models.CharField(choices=[('management', 'Management'), ('volunteer', 'Volunteer'), ('foodbank', 'Food Bank Storage')], default='management', max_length=20),
        ),
    ]
