# Generated by Django 6.0.6 on 2026-07-15 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_stockmovement_context'),
        ('kitchens', '0003_remove_kitchen_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='context',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='location',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='kitchen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='kitchens.kitchen'),
        ),
    ]
