# Generated by Django 6.0.6 on 2026-07-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_stockmovement_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='transfer_group',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
