# Generated by Django 6.0.6 on 2026-07-16 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_stockmovement_transfer_group'),
        ('kitchens', '0003_remove_kitchen_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrequest',
            name='kitchen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kitchens.kitchen'),
        ),
    ]
