# Generated by Django 6.0.6 on 2026-07-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_inventoryrequest_kitchen'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='is_foodbank',
            field=models.BooleanField(default=False),
        ),
    ]
