# Generated by Django 6.0.6 on 2026-07-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_usagelog_kitchenstockstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='package_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='e.g. 5.00 for a 5kg bag, 1.00 for a 1L bottle.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Reference/default price per package (or per unit if no package_size). Used to estimate stock value; actual purchase price per movement is tracked on StockMovement.unit_price.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inventoryrequest',
            name='new_item_package_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='inventoryrequest',
            name='new_item_price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
