# Generated by Django 6.0.6 on 2026-07-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_inventoryitem_package_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagelog',
            name='usage_unit',
            field=models.CharField(choices=[('cup', 'Cup'), ('pack', 'Pack'), ('piece', 'Piece'), ('bowl', 'Bowl'), ('plate', 'Plate'), ('bottle', 'Bottle'), ('sachet', 'Sachet'), ('tin', 'Tin'), ('kg', 'Kg'), ('g', 'Gram'), ('l', 'Liter'), ('ml', 'ml'), ('other', 'Other')], default='cup', max_length=20),
        ),
    ]
