# Generated by Django 6.0.3 on 2026-07-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchenslot',
            name='max_capacity',
            field=models.IntegerField(default=2),
        ),
    ]
