# Generated by Django 6.0.6 on 2026-07-16 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_bookingparticipant'),
        ('kitchens', '0003_remove_kitchen_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenslot',
            name='kitchen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='kitchens.kitchen'),
        ),
    ]
