# Generated by Django 6.0.6 on 2026-07-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_kitchenslot_kitchen'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingparticipant',
            name='faculty',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
