# Generated by Django 6.0.6 on 2026-07-16 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('booking', '0003_bookingparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='kitchen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='booking.kitchenslot'),
        ),
    ]
