# Generated by Django 6.0.6 on 2026-07-16 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancerecord_kitchen'),
        ('kitchens', '0003_remove_kitchen_manager'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendancerecord',
            name='unique_student_attendance',
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='kitchen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='kitchens.kitchen'),
        ),
    ]
