# Generated by Django 6.0.6 on 2026-07-18 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_attendancerecord_unique_student_attendance_and_more'),
        ('inventory', '0013_stockmovement_is_foodbank'),
        ('kitchens', '0003_remove_kitchen_manager'),
        ('students', '0003_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('took_rice', models.BooleanField(default=False)),
                ('took_dish', models.BooleanField(default=False)),
                ('took_foodbank', models.BooleanField(default=False)),
                ('used_kitchen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='attendance.attendancerecord')),
                ('kitchen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kitchens.kitchen')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='FoodbankTakenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodbank_items', to='attendance.studentactivity')),
            ],
        ),
    ]
