# Generated by Django 6.0.6 on 2026-07-25 05:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kitchens', '0003_remove_kitchen_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStorageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('date_stored', models.DateField(default=django.utils.timezone.localdate, help_text='The day the item was put into storage.')),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='student_storage_proofs/')),
                ('status', models.CharField(choices=[('stored', 'Stored'), ('removed', 'Removed'), ('expired', 'Expired')], default='stored', max_length=20)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_storage_logs', to='kitchens.kitchen')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_stored', '-created_at'],
            },
        ),
    ]
